# Generated by Django 5.2.4 on 2025-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('banner_image', models.ImageField(upload_to='promotion_banners/', verbose_name='Изображение баннера')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли акция')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
