services:
  web:
    build: .
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=furetracker.settings
    expose:
      - "8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - nginx_logs:/var/log/nginx/
    depends_on:
      web:
        condition: service_started
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_mebel -d mebeldata"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  django_logs:
  nginx_logs:
  postgres_data: