services:
  web:
    build: .
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=furetracker.settings
    expose:
      - "8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - nginx_logs:/var/log/nginx/
      # Теперь используем именованные тома для Certbot
      - certbot_etc:/etc/letsencrypt # Сертификаты Certbot
      - certbot_var:/var/lib/letsencrypt # Данные Certbot
      - certbot_www:/var/www/certbot # Для проверки владения доменом
    depends_on:
      web:
        condition: service_started
    restart: always

  certbot: # НОВЫЙ СЕРВИС CERTBOT
    image: certbot/certbot
    volumes:
      - certbot_etc:/etc/letsencrypt # <-- Изменить
      - certbot_var:/var/lib/letsencrypt # <-- Изменить
      - certbot_www:/var/www/certbot # <-- Изменить
    depends_on:
      - nginx
    command: "certonly --webroot -w /var/www/certbot -d baizhigit-mebel.kz -d www.baizhigit-mebel.kz --email zivichchanel01@gmail.com --rsa-key-size 4096 --agree-tos --no-eff-email --force-renewal" # Замените на ваши домены и email!

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_mebel -d mebeldata"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  django_logs:
  nginx_logs:
  postgres_data:
  certbot_etc: # Новый том для /etc/letsencrypt
  certbot_var: # Новый том для /var/lib/letsencrypt
  certbot_www: # Новый том для /var/www/certbot