# Generated by Django 5.2.4 on 2025-08-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_text', models.CharField(default='АКЦИЯ: Скидки до 30% на все товары!', max_length=255, verbose_name='Текст акции в шапке сайта')),
                ('instagram_link', models.URLField(default='https://www.instagram.com/baizhigit_mebel', max_length=255, verbose_name='Ссылка на инстаграм')),
                ('whatsapp_link', models.URLField(default='https://wa.me/77783244835', max_length=255, verbose_name='Ссылка на WhatsApp')),
                ('main_index_text', models.CharField(default='Творим Дома <br> Из Мечты', max_length=150, verbose_name='Текст на главной странице')),
                ('second_index_text', models.CharField(default='Ваш идеальный интерьер начинается с мебели, созданной специально для вас.', max_length=150, verbose_name='Вторичный текст на странице')),
                ('business_age', models.IntegerField(default=0, help_text='15', verbose_name='Возраст бизнеса')),
                ('telephone_number', models.CharField(default='+7 (778) 324-48-35', max_length=15, verbose_name='Номер телефона')),
                ('address', models.CharField(default='Проспект Акжол, 20', max_length=255, verbose_name='Адрес')),
                ('twogis_link', models.URLField(default='https://go.2gis.com/9fZTM', max_length=255, verbose_name='Ссылка на 2GIS')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
