# Generated by Django 5.2.4 on 2025-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='business_age',
            field=models.IntegerField(default=15, help_text='15', verbose_name='Возраст бизнеса'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telephone_number',
            field=models.CharField(default='+7 (778) 324-48-35', max_length=150, verbose_name='Номер телефона'),
        ),
    ]
