# Generated by Django 5.2.4 on 2025-08-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на консультацию', 'verbose_name_plural': 'Заявки на консультацию'},
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Консультант'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='is_relevant',
            field=models.BooleanField(default=False, verbose_name='Актуально после консультации'),
        ),
    ]
