# Generated by Django 5.2.4 on 2025-07-28 15:56

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_comment_options_alter_comment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=orders.models.order_media_upload_to),
        ),
    ]
