# Generated by Django 5.2.4 on 2025-08-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordermedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_employees',
            field=models.TextField(blank=True, help_text='Имена сотрудников, работающих над заказом, их роли или любые другие связанные пометки.', null=True, verbose_name='Назначенные сотрудники'),
        ),
    ]
