# Generated by Django 5.2.4 on 2025-08-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_stage_completion_date_order_stage_design_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stage_completion_date',
            field=models.DateField(blank=True, help_text='Дата, когда заказ был завершен и готов к выдаче.', null=True, verbose_name='Дата завершения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage_design_date',
            field=models.DateField(blank=True, help_text='Дата, когда дизайн был утвержден.', null=True, verbose_name='Дата утверждения дизайна'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage_measurement_date',
            field=models.DateField(blank=True, help_text='Дата, когда был произведен замер.', null=True, verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage_technologist_date',
            field=models.DateField(blank=True, help_text='Дата, когда технолог завершил свою часть работы.', null=True, verbose_name='Дата работы технолога'),
        ),
    ]
