# Generated by Django 5.2.4 on 2025-08-12 08:23

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_stage_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedia',
            name='file',
            field=models.FileField(upload_to=orders.models.order_media_upload_to),
        ),
    ]
