# Generated by Django 5.2.4 on 2026-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_ordermedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Если включено, заказ виден всем на сайте в разделе «Портфолио» (без комментариев). Иначе заказ открывается только по личной ссылке клиента.', verbose_name='Показывать в портфолио'),
        ),
    ]
